import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NodeRSA from 'node-rsa'
import { TextField } from '@mui/material'
import { Box } from '@mui/system'
import { useState } from 'react'

const Home: NextPage = () => {
  const [texto,setTexto] = useState('')
  const [textoEncriptado,setTextoEncriptado] = useState('')
  
  function encrypt(){
    const key = new NodeRSA({b: 512});
    const encrypted = key.encrypt(texto, 'base64');
    setTextoEncriptado(encrypted)
  }
  function decrypt(){
    const key = new NodeRSA({b: 512});
    const decrypted = key.decrypt(textoEncriptado, 'utf8');
    console.log(decrypted)
    setTexto(decrypted)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Criptografia com algoritmo <a>RSA</a>
        </h1>

        <p className={styles.description}>
            <TextField 
              value={texto}
              onChange={(e)=> setTexto(e.target.value)}
              className={styles.inputTexto} 
              id="standard-basic" 
              label="Texto" 
              variant="standard" 
            />
            <TextField 
              value={textoEncriptado}
              onChange={(e)=> setTextoEncriptado(e.target.value)}
              style={{"width":"300px"}}
              id="standard-basic" 
              label="Texto criptografado" 
              variant="standard" 
            />

        </p>

        <div className={styles.grid}>
          <a className={styles.card}
            onClick={encrypt}
          >
            <h2>Encriptar &rarr;</h2>
          </a>

          <a className={styles.card}
            onClick={decrypt}
          >
            <h2>Desencriptar &larr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
